# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-18 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0003_auto_20191018_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
