# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ig', '0008_auto_20191020_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
